### ISSUE TITLE
评论系统似乎无法使用

### ISSUE THREAD

**Issue by Similarityoung** [HADB/hadb.me#24]
描述:

在使用 Artalk 加载评论时，我遇到了以下错误信息：

错误信息:
Artalk 错误
无法加载评论
TypeError: Failed to fetch
这个问题导致评论部分无法正常显示和互动。
![image](https://github.com/user-attachments/assets/32f5918f-b5f5-4095-b500-716d1ad1e46f)

**Comment by HADB** [comment]
感谢反馈，修好了，一个代理的 nginx 出了点问题
